<a href="https://colab.research.google.com/github/setyo-dwi-pratama/covid-19/blob/master/covid_global.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [4]:
#Kasus Global Terkonfirmasi Positif Covid-19
dfc = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_confirmed_global.csv")

In [5]:
dfc.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...    27878    28424    28833
1            NaN        Albania  41.1533  ...     1838     1891     1962
2            NaN        Algeria  28.0339  ...    11504    11631    11771
3            NaN        Andorra  42.5063  ...      855      855      855
4            NaN         Angola -11.2027  ...      172      176      183

[5 rows x 156 columns]

In [6]:
#Kasus Global Sembuh Covid-19
dfr = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_recovered_global.csv")
#Kasus Global Meninggal Covid-19
dfd = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_deaths_global.csv")

In [7]:
dfr.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...     7962     8292     8764
1            NaN        Albania  41.1533  ...     1114     1126     1134
2            NaN        Algeria  28.0339  ...     8196     8324     8422
3            NaN        Andorra  42.5063  ...      792      792      792
4            NaN         Angola -11.2027  ...       66       66       77

[5 rows x 156 columns]

In [8]:
dfd.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...      548      569      581
1            NaN        Albania  41.1533  ...       42       43       44
2            NaN        Algeria  28.0339  ...      825      837      845
3            NaN        Andorra  42.5063  ...       52       52       52
4            NaN         Angola -11.2027  ...        8        9        9

[5 rows x 156 columns]

# Cleaning Data

Menghapus Kolom Provinsi

In [9]:
del dfc["Province/State"]

In [10]:
del dfr["Province/State"]

In [11]:
del dfd["Province/State"]

Mengecek jumlah banyaknya dataset

In [12]:
dfc.shape

(266, 155)

In [13]:
dfr.shape

(253, 155)

In [14]:
dfd.shape

(266, 155)

dapat dilihat bahwa dataset positif dan sembuh tidak seimbang

In [15]:
compere = set(dfc["Country/Region"]).intersection(set(dfr["Country/Region"]))

In [16]:
len(compere)

188

In [17]:
compere = set(dfc["Country/Region"]).union(set(dfr["Country/Region"]))

In [18]:
len(compere)

188

In [19]:
compere = set(dfc["Country/Region"]).difference(set(dfr["Country/Region"]))

In [20]:
len(compere)

0

Cek Data dari perbedadaan banyak data antara dfc dan dfr

index ke berapa ada data yang tidak sama di dfc dan dfr?

In [21]:
list_beda=[] #menyimpan index yang datanya tidak sama antara dfc dan dfr
def cekdata(a,b):
  for i in range(len(b)):
    if (a.iloc[i]["Country/Region"]) != (b.iloc[i]["Country/Region"]):
         list_beda.append(i)
  return list_beda
cek = cekdata(dfc,dfr)
cek

[24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252]

In [22]:
list_cek=[]
all_cek=[]
for c in range(len(cek)):
  list_cek=dfc.iloc[[cek[c]]]["Country/Region"].values.tolist(),dfr.iloc[[cek[c]]]["Country/Region"].values.tolist()
  all_cek.append(list_cek)
all_cek

[(['Benin'], ['Belize']),
 (['Bhutan'], ['Benin']),
 (['Bolivia'], ['Bhutan']),
 (['Bosnia and Herzegovina'], ['Bolivia']),
 (['Brazil'], ['Bosnia and Herzegovina']),
 (['Brunei'], ['Brazil']),
 (['Bulgaria'], ['Brunei']),
 (['Burkina Faso'], ['Bulgaria']),
 (['Cabo Verde'], ['Burkina Faso']),
 (['Cambodia'], ['Cabo Verde']),
 (['Cameroon'], ['Cambodia']),
 (['Canada'], ['Cameroon']),
 (['Canada'], ['Central African Republic']),
 (['Canada'], ['Chad']),
 (['Canada'], ['Chile']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Central African Republic'], ['China']),
 (['Chad'], ['China']),
 (['Chile'], ['China']),
 (['China'], ['Colombia']),
 (['China'], ['Congo (Brazzaville)']),
 (['China'], ['Congo (Kinshasa)']),
 (['China'], ['Costa Rica']),
 (['China'], ["Cote d'Ivoire"]),
 (['China'], ['Croatia']),
 (['China'], ['Diamond Princess']),
 (['China'], ['Cuba']),
 (['China'], ['Cyprus']),
 (['Colombia'], ['Czechia']),
 (['Congo (Brazzaville)'], ['Denmark']),
 (['Congo (Kinshasa)'], ['Denmark']),
 (['Costa Rica'], ['Denmark']),
 (["Cote d'Ivoire"], ['Djibouti']),
 (['Croatia'], ['Dominica']),
 (['Diamond Princess'], ['Dominican Republic']),
 (['Cuba'], ['Ecuador']),
 (['Cyprus'], ['Egypt']),
 (['Czechia'], ['El Salvador']),
 (['Denmark'], ['Equatorial Guinea']),
 (['Denmark'], ['Eritrea']),
 (['Denmark'], ['Estonia']),
 (['Djibouti'], ['Eswatini']),
 (['Dominican Republic'], ['Ethiopia']),
 (['Ecuador'], ['Fiji']),
 (['Egypt'], ['Finland']),
 (['El Salvador'], ['France']),
 (['Equatorial Guinea'], ['France']),
 (['Eritrea'], ['France']),
 (['Estonia'], ['France']),
 (['Eswatini'], ['France']),
 (['Ethiopia'], ['France']),
 (['Fiji'], ['France']),
 (['Finland'], ['France']),
 (['France'], ['Gabon']),
 (['France'], ['Gambia']),
 (['France'], ['Georgia']),
 (['France'], ['Germany']),
 (['France'], ['Ghana']),
 (['France'], ['Grenada']),
 (['France'], ['Greece']),
 (['France'], ['Guatemala']),
 (['Gabon'], ['Guinea']),
 (['Gambia'], ['Guinea-Bissau']),
 (['Georgia'], ['Guyana']),
 (['Germany'], ['Haiti']),
 (['Ghana'], ['Holy See']),
 (['Greece'], ['Honduras']),
 (['Guatemala'], ['Hungary']),
 (['Guinea'], ['Iceland']),
 (['Guyana'], ['India']),
 (['Haiti'], ['Indonesia']),
 (['Holy See'], ['Iran']),
 (['Honduras'], ['Iraq']),
 (['Hungary'], ['Ireland']),
 (['Iceland'], ['Israel']),
 (['India'], ['Italy']),
 (['Indonesia'], ['Jamaica']),
 (['Iran'], ['Japan']),
 (['Iraq'], ['Jordan']),
 (['Ireland'], ['Kazakhstan']),
 (['Israel'], ['Kenya']),
 (['Italy'], ['Korea, South']),
 (['Jamaica'], ['Kuwait']),
 (['Japan'], ['Kyrgyzstan']),
 (['Jordan'], ['Latvia']),
 (['Kazakhstan'], ['Lebanon']),
 (['Kenya'], ['Liberia']),
 (['Korea, South'], ['Libya']),
 (['Kuwait'], ['Liechtenstein']),
 (['Kyrgyzstan'], ['Lithuania']),
 (['Latvia'], ['Luxembourg']),
 (['Lebanon'], ['Madagascar']),
 (['Liberia'], ['Malaysia']),
 (['Liechtenstein'], ['Maldives']),
 (['Lithuania'], ['Mali']),
 (['Luxembourg'], ['Malta']),
 (['Madagascar'], ['Mauritania']),
 (['Malaysia'], ['Mauritius']),
 (['Maldives'], ['Mexico']),
 (['Malta'], ['Moldova']),
 (['Mauritania'], ['Monaco']),
 (['Mauritius'], ['Mongolia']),
 (['Mexico'], ['Montenegro']),
 (['Moldova'], ['Morocco']),
 (['Monaco'], ['Mozambique']),
 (['Mongolia'], ['Namibia']),
 (['Montenegro'], ['Nepal']),
 (['Morocco'], ['Netherlands']),
 (['Namibia'], ['Netherlands']),
 (['Nepal'], ['Netherlands']),
 (['Netherlands'], ['New Zealand']),
 (['Netherlands'], ['Nicaragua']),
 (['Netherlands'], ['Niger']),
 (['New Zealand'], ['Nigeria']),
 (['Nicaragua'], ['North Macedonia']),
 (['Niger'], ['Norway']),
 (['Nigeria'], ['Oman']),
 (['North Macedonia'], ['Pakistan']),
 (['Norway'], ['Panama']),
 (['Oman'], ['Papua New Guinea']),
 (['Pakistan'], ['Paraguay']),
 (['Panama'], ['Peru']),
 (['Papua New Guinea'], ['Philippines']),
 (['Paraguay'], ['Poland']),
 (['Peru'], ['Portugal']),
 (['Philippines'], ['Qatar']),
 (['Poland'], ['Romania']),
 (['Portugal'], ['Russia']),
 (['Qatar'], ['Rwanda']),
 (['Romania'], ['Saint Kitts and Nevis']),
 (['Russia'], ['Saint Lucia']),
 (['Rwanda'], ['Saint Vincent and the Grenadines']),
 (['Saint Lucia'], ['San Marino']),
 (['Saint Vincent and the Grenadines'], ['Saudi Arabia']),
 (['San Marino'], ['Senegal']),
 (['Saudi Arabia'], ['Serbia']),
 (['Senegal'], ['Seychelles']),
 (['Serbia'], ['Singapore']),
 (['Seychelles'], ['Slovakia']),
 (['Singapore'], ['Slovenia']),
 (['Slovakia'], ['Somalia']),
 (['Slovenia'], ['South Africa']),
 (['Somalia'], ['Spain']),
 (['South Africa'], ['Sri Lanka']),
 (['Spain'], ['Sudan']),
 (['Sri Lanka'], ['Suriname']),
 (['Sudan'], ['Sweden']),
 (['Suriname'], ['Switzerland']),
 (['Sweden'], ['Syria']),
 (['Switzerland'], ['Taiwan*']),
 (['Taiwan*'], ['Tanzania']),
 (['Tanzania'], ['Thailand']),
 (['Thailand'], ['Timor-Leste']),
 (['Canada'], ['West Bank and Gaza']),
 (['Dominica'], ['Laos']),
 (['Grenada'], ['Kosovo']),
 (['Mozambique'], ['Burma']),
 (['Syria'], ['United Kingdom']),
 (['Timor-Leste'], ['United Kingdom']),
 (['Belize'], ['United Kingdom']),
 (['Laos'], ['MS Zaandam']),
 (['Libya'], ['Botswana']),
 (['West Bank and Gaza'], ['Burundi']),
 (['Guinea-Bissau'], ['Sierra Leone']),
 (['Mali'], ['Netherlands']),
 (['Saint Kitts and Nevis'], ['Malawi']),
 (['Canada'], ['United Kingdom']),
 (['Canada'], ['France']),
 (['Kosovo'], ['South Sudan']),
 (['Burma'], ['Western Sahara']),
 (['United Kingdom'], ['Sao Tome and Principe']),
 (['United Kingdom'], ['Yemen']),
 (['United Kingdom'], ['Comoros']),
 (['MS Zaandam'], ['Tajikistan']),
 (['Botswana'], ['Lesotho'])]

Liat posisi "Belize" disejajarkan dengan "Benin"?

apakah ada "Belize" di daftar dfc

In [23]:
listb = dfc["Country/Region"].values
"Belize" in listb

True

Sort semua dataframe

In [29]:
dfc.sort_values("Country/Region", inplace=True, ignore_index=True)
dfr.sort_values("Country/Region", inplace=True, ignore_index=True)
dfd.sort_values("Country/Region", inplace=True, ignore_index=True)

In [30]:
dfc

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...    27878    28424    28833
1               Albania  41.153300  20.168300  ...     1838     1891     1962
2               Algeria  28.033900   1.659600  ...    11504    11631    11771
3               Andorra  42.506300   1.521800  ...      855      855      855
4                Angola -11.202700  17.873900  ...      172      176      183
..                  ...        ...        ...  ...      ...      ...      ...
261  West Bank and Gaza  31.952200  35.233200  ...      675      784      833
262      Western Sahara  24.215500 -12.885800  ...        9        9        9
263               Yemen  15.552727  48.516388  ...      919      922      941
264              Zambia -15.416700  28.283300  ...     1430     1430     1430
265            Zimbabwe -20.000000  30.000000  ...      479      479      489

[266 rows x 155 columns]

In [31]:
dfr

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...     7962     8292     8764
1               Albania  41.153300  20.168300  ...     1114     1126     1134
2               Algeria  28.033900   1.659600  ...     8196     8324     8422
3               Andorra  42.506300   1.521800  ...      792      792      792
4                Angola -11.202700  17.873900  ...       66       66       77
..                  ...        ...        ...  ...      ...      ...      ...
248  West Bank and Gaza  31.952200  35.233200  ...      437      437      439
249      Western Sahara  24.215500 -12.885800  ...        8        8        8
250               Yemen  15.552727  48.516388  ...      288      328      347
251              Zambia -15.416700  28.283300  ...     1194     1194     1194
252            Zimbabwe -20.000000  30.000000  ...       63       63       64

[253 rows x 155 columns]

In [32]:
dfd

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...      548      569      581
1               Albania  41.153300  20.168300  ...       42       43       44
2               Algeria  28.033900   1.659600  ...      825      837      845
3               Andorra  42.506300   1.521800  ...       52       52       52
4                Angola -11.202700  17.873900  ...        8        9        9
..                  ...        ...        ...  ...      ...      ...      ...
261  West Bank and Gaza  31.952200  35.233200  ...        3        3        3
262      Western Sahara  24.215500 -12.885800  ...        1        1        1
263               Yemen  15.552727  48.516388  ...      251      254      256
264              Zambia -15.416700  28.283300  ...       11       11       11
265            Zimbabwe -20.000000  30.000000  ...        4        4        6

[266 rows x 155 columns]

Cek Kembali

In [33]:
dfc.shape

(266, 155)

In [34]:
dfr.shape

(253, 155)

Menggabungkan data dari semua dataset dfc, dfr, dan dfd

In [37]:
dfc.loc[dfc["Country/Region"] == "Australia"]
#dfr.loc[dfc["Country/Region"] == "Australia"]
#dfd.loc[dfc["Country/Region"] == "Australia"]

   Country/Region      Lat      Long  ...  6/19/20  6/20/20  6/21/20
8       Australia -28.0167  153.4000  ...     1066     1066     1066
9       Australia -37.8136  144.9631  ...     1792     1836     1847
10      Australia -41.4545  145.9707  ...      228      228      228
11      Australia -35.4735  149.0124  ...      108      108      108
12      Australia -12.4634  130.8456  ...       29       29       29
13      Australia -33.8688  151.2093  ...     3144     3149     3151
14      Australia -34.9285  138.6007  ...      440      440      440
15      Australia -31.9505  115.8605  ...      604      605      605

[8 rows x 155 columns]

In [39]:
Australi = dfc.loc[dfc["Country/Region"] == "Australia"].sum()[3:]
Australi

1/22/20       0
1/23/20       0
1/24/20       0
1/25/20       0
1/26/20       4
           ...
6/17/20    7391
6/18/20    7409
6/19/20    7411
6/20/20    7461
6/21/20    7474
Length: 152, dtype: object

In [40]:
Indonesia = dfc.loc[dfc["Country/Region"] == "Indonesia"].sum()[3:]
Indonesia

1/22/20        0
1/23/20        0
1/24/20        0
1/25/20        0
1/26/20        0
           ...
6/17/20    41431
6/18/20    42762
6/19/20    43803
6/20/20    45029
6/21/20    45891
Length: 152, dtype: object

In [45]:
latitude = dfc.loc[dfc["Country/Region"] == "Australia"].mean().values.tolist()[0:2]
latitude

[-31.9961875, 141.23278749999997]

Membuat fungsi untuk menjalankan secara otomatis

In [ ]:
def hitungSum(dfx, idx):
  nama_negara=list(dfx[idx].unique)