<a href="https://colab.research.google.com/github/setyo-dwi-pratama/covid-19/blob/master/covid_global.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

/usr/local/lib/python3.6/dist-packages/statsmodels/tools/_testing.py:19: FutureWarning: pandas.util.testing is deprecated. Use the functions in the public API at pandas.testing instead.
  import pandas.util.testing as tm

In [2]:
#Kasus Global Terkonfirmasi Positif Covid-19
dfc = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_confirmed_global.csv")

In [3]:
dfc.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...    27878    28424    28833
1            NaN        Albania  41.1533  ...     1838     1891     1962
2            NaN        Algeria  28.0339  ...    11504    11631    11771
3            NaN        Andorra  42.5063  ...      855      855      855
4            NaN         Angola -11.2027  ...      172      176      183

[5 rows x 156 columns]

In [4]:
#Kasus Global Sembuh Covid-19
dfr = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_recovered_global.csv")
#Kasus Global Meninggal Covid-19
dfd = pd.read_csv("https://raw.githubusercontent.com/setyo-dwi-pratama/covid-19/master/time_series_covid19_deaths_global.csv")

In [5]:
dfr.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...     7962     8292     8764
1            NaN        Albania  41.1533  ...     1114     1126     1134
2            NaN        Algeria  28.0339  ...     8196     8324     8422
3            NaN        Andorra  42.5063  ...      792      792      792
4            NaN         Angola -11.2027  ...       66       66       77

[5 rows x 156 columns]

In [6]:
dfd.head()

  Province/State Country/Region      Lat  ...  6/19/20  6/20/20  6/21/20
0            NaN    Afghanistan  33.0000  ...      548      569      581
1            NaN        Albania  41.1533  ...       42       43       44
2            NaN        Algeria  28.0339  ...      825      837      845
3            NaN        Andorra  42.5063  ...       52       52       52
4            NaN         Angola -11.2027  ...        8        9        9

[5 rows x 156 columns]

# Cleaning Data

Menghapus Kolom Provinsi

In [7]:
del dfc["Province/State"]

In [8]:
del dfr["Province/State"]

In [9]:
del dfd["Province/State"]

Mengecek jumlah banyaknya dataset

In [10]:
dfc.shape

(266, 155)

In [11]:
dfr.shape

(253, 155)

In [12]:
dfd.shape

(266, 155)

dapat dilihat bahwa dataset positif dan sembuh tidak seimbang

In [13]:
compere = set(dfc["Country/Region"]).intersection(set(dfr["Country/Region"]))

In [14]:
len(compere)

188

In [15]:
compere = set(dfc["Country/Region"]).union(set(dfr["Country/Region"]))

In [16]:
len(compere)

188

In [17]:
compere = set(dfc["Country/Region"]).difference(set(dfr["Country/Region"]))

In [18]:
len(compere)

0

Cek Data dari perbedadaan banyak data antara dfc dan dfr

index ke berapa ada data yang tidak sama di dfc dan dfr?

In [19]:
list_beda=[] #menyimpan index yang datanya tidak sama antara dfc dan dfr
def cekdata(a,b):
  for i in range(len(b)):
    if (a.iloc[i]["Country/Region"]) != (b.iloc[i]["Country/Region"]):
         list_beda.append(i)
  return list_beda
cek = cekdata(dfc,dfr)
cek

[24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99,
 100,
 101,
 102,
 103,
 104,
 105,
 106,
 109,
 110,
 111,
 112,
 113,
 114,
 115,
 116,
 117,
 118,
 119,
 120,
 121,
 122,
 123,
 124,
 125,
 126,
 127,
 128,
 129,
 130,
 131,
 132,
 133,
 134,
 135,
 136,
 137,
 138,
 139,
 140,
 141,
 142,
 143,
 144,
 145,
 146,
 147,
 148,
 149,
 150,
 151,
 152,
 153,
 154,
 155,
 156,
 157,
 158,
 159,
 160,
 161,
 162,
 163,
 164,
 165,
 167,
 168,
 169,
 170,
 171,
 172,
 173,
 174,
 175,
 176,
 177,
 178,
 179,
 180,
 181,
 182,
 183,
 184,
 185,
 186,
 187,
 188,
 189,
 190,
 191,
 192,
 193,
 194,
 195,
 196,
 197,
 198,
 199,
 200,
 201,
 202,
 203,
 204,
 205,
 206,
 207,
 208,
 209,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252]

In [20]:
list_cek=[]
all_cek=[]
for c in range(len(cek)):
  list_cek=dfc.iloc[[cek[c]]]["Country/Region"].values.tolist(),dfr.iloc[[cek[c]]]["Country/Region"].values.tolist()
  all_cek.append(list_cek)
all_cek

[(['Benin'], ['Belize']),
 (['Bhutan'], ['Benin']),
 (['Bolivia'], ['Bhutan']),
 (['Bosnia and Herzegovina'], ['Bolivia']),
 (['Brazil'], ['Bosnia and Herzegovina']),
 (['Brunei'], ['Brazil']),
 (['Bulgaria'], ['Brunei']),
 (['Burkina Faso'], ['Bulgaria']),
 (['Cabo Verde'], ['Burkina Faso']),
 (['Cambodia'], ['Cabo Verde']),
 (['Cameroon'], ['Cambodia']),
 (['Canada'], ['Cameroon']),
 (['Canada'], ['Central African Republic']),
 (['Canada'], ['Chad']),
 (['Canada'], ['Chile']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Canada'], ['China']),
 (['Central African Republic'], ['China']),
 (['Chad'], ['China']),
 (['Chile'], ['China']),
 (['China'], ['Colombia']),
 (['China'], ['Congo (Brazzaville)']),
 (['China'], ['Congo (Kinshasa)']),
 (['China'], ['Costa Rica']),
 (['China'], ["Cote d'Ivoire"]),
 (['China'], ['Croatia']),
 (['China'], ['Diamond Princess']),
 (['China'], ['Cuba']),
 (['China'], ['Cyprus']),
 (['Colombia'], ['Czechia']),
 (['Congo (Brazzaville)'], ['Denmark']),
 (['Congo (Kinshasa)'], ['Denmark']),
 (['Costa Rica'], ['Denmark']),
 (["Cote d'Ivoire"], ['Djibouti']),
 (['Croatia'], ['Dominica']),
 (['Diamond Princess'], ['Dominican Republic']),
 (['Cuba'], ['Ecuador']),
 (['Cyprus'], ['Egypt']),
 (['Czechia'], ['El Salvador']),
 (['Denmark'], ['Equatorial Guinea']),
 (['Denmark'], ['Eritrea']),
 (['Denmark'], ['Estonia']),
 (['Djibouti'], ['Eswatini']),
 (['Dominican Republic'], ['Ethiopia']),
 (['Ecuador'], ['Fiji']),
 (['Egypt'], ['Finland']),
 (['El Salvador'], ['France']),
 (['Equatorial Guinea'], ['France']),
 (['Eritrea'], ['France']),
 (['Estonia'], ['France']),
 (['Eswatini'], ['France']),
 (['Ethiopia'], ['France']),
 (['Fiji'], ['France']),
 (['Finland'], ['France']),
 (['France'], ['Gabon']),
 (['France'], ['Gambia']),
 (['France'], ['Georgia']),
 (['France'], ['Germany']),
 (['France'], ['Ghana']),
 (['France'], ['Grenada']),
 (['France'], ['Greece']),
 (['France'], ['Guatemala']),
 (['Gabon'], ['Guinea']),
 (['Gambia'], ['Guinea-Bissau']),
 (['Georgia'], ['Guyana']),
 (['Germany'], ['Haiti']),
 (['Ghana'], ['Holy See']),
 (['Greece'], ['Honduras']),
 (['Guatemala'], ['Hungary']),
 (['Guinea'], ['Iceland']),
 (['Guyana'], ['India']),
 (['Haiti'], ['Indonesia']),
 (['Holy See'], ['Iran']),
 (['Honduras'], ['Iraq']),
 (['Hungary'], ['Ireland']),
 (['Iceland'], ['Israel']),
 (['India'], ['Italy']),
 (['Indonesia'], ['Jamaica']),
 (['Iran'], ['Japan']),
 (['Iraq'], ['Jordan']),
 (['Ireland'], ['Kazakhstan']),
 (['Israel'], ['Kenya']),
 (['Italy'], ['Korea, South']),
 (['Jamaica'], ['Kuwait']),
 (['Japan'], ['Kyrgyzstan']),
 (['Jordan'], ['Latvia']),
 (['Kazakhstan'], ['Lebanon']),
 (['Kenya'], ['Liberia']),
 (['Korea, South'], ['Libya']),
 (['Kuwait'], ['Liechtenstein']),
 (['Kyrgyzstan'], ['Lithuania']),
 (['Latvia'], ['Luxembourg']),
 (['Lebanon'], ['Madagascar']),
 (['Liberia'], ['Malaysia']),
 (['Liechtenstein'], ['Maldives']),
 (['Lithuania'], ['Mali']),
 (['Luxembourg'], ['Malta']),
 (['Madagascar'], ['Mauritania']),
 (['Malaysia'], ['Mauritius']),
 (['Maldives'], ['Mexico']),
 (['Malta'], ['Moldova']),
 (['Mauritania'], ['Monaco']),
 (['Mauritius'], ['Mongolia']),
 (['Mexico'], ['Montenegro']),
 (['Moldova'], ['Morocco']),
 (['Monaco'], ['Mozambique']),
 (['Mongolia'], ['Namibia']),
 (['Montenegro'], ['Nepal']),
 (['Morocco'], ['Netherlands']),
 (['Namibia'], ['Netherlands']),
 (['Nepal'], ['Netherlands']),
 (['Netherlands'], ['New Zealand']),
 (['Netherlands'], ['Nicaragua']),
 (['Netherlands'], ['Niger']),
 (['New Zealand'], ['Nigeria']),
 (['Nicaragua'], ['North Macedonia']),
 (['Niger'], ['Norway']),
 (['Nigeria'], ['Oman']),
 (['North Macedonia'], ['Pakistan']),
 (['Norway'], ['Panama']),
 (['Oman'], ['Papua New Guinea']),
 (['Pakistan'], ['Paraguay']),
 (['Panama'], ['Peru']),
 (['Papua New Guinea'], ['Philippines']),
 (['Paraguay'], ['Poland']),
 (['Peru'], ['Portugal']),
 (['Philippines'], ['Qatar']),
 (['Poland'], ['Romania']),
 (['Portugal'], ['Russia']),
 (['Qatar'], ['Rwanda']),
 (['Romania'], ['Saint Kitts and Nevis']),
 (['Russia'], ['Saint Lucia']),
 (['Rwanda'], ['Saint Vincent and the Grenadines']),
 (['Saint Lucia'], ['San Marino']),
 (['Saint Vincent and the Grenadines'], ['Saudi Arabia']),
 (['San Marino'], ['Senegal']),
 (['Saudi Arabia'], ['Serbia']),
 (['Senegal'], ['Seychelles']),
 (['Serbia'], ['Singapore']),
 (['Seychelles'], ['Slovakia']),
 (['Singapore'], ['Slovenia']),
 (['Slovakia'], ['Somalia']),
 (['Slovenia'], ['South Africa']),
 (['Somalia'], ['Spain']),
 (['South Africa'], ['Sri Lanka']),
 (['Spain'], ['Sudan']),
 (['Sri Lanka'], ['Suriname']),
 (['Sudan'], ['Sweden']),
 (['Suriname'], ['Switzerland']),
 (['Sweden'], ['Syria']),
 (['Switzerland'], ['Taiwan*']),
 (['Taiwan*'], ['Tanzania']),
 (['Tanzania'], ['Thailand']),
 (['Thailand'], ['Timor-Leste']),
 (['Canada'], ['West Bank and Gaza']),
 (['Dominica'], ['Laos']),
 (['Grenada'], ['Kosovo']),
 (['Mozambique'], ['Burma']),
 (['Syria'], ['United Kingdom']),
 (['Timor-Leste'], ['United Kingdom']),
 (['Belize'], ['United Kingdom']),
 (['Laos'], ['MS Zaandam']),
 (['Libya'], ['Botswana']),
 (['West Bank and Gaza'], ['Burundi']),
 (['Guinea-Bissau'], ['Sierra Leone']),
 (['Mali'], ['Netherlands']),
 (['Saint Kitts and Nevis'], ['Malawi']),
 (['Canada'], ['United Kingdom']),
 (['Canada'], ['France']),
 (['Kosovo'], ['South Sudan']),
 (['Burma'], ['Western Sahara']),
 (['United Kingdom'], ['Sao Tome and Principe']),
 (['United Kingdom'], ['Yemen']),
 (['United Kingdom'], ['Comoros']),
 (['MS Zaandam'], ['Tajikistan']),
 (['Botswana'], ['Lesotho'])]

Liat posisi "Belize" disejajarkan dengan "Benin"?

apakah ada "Belize" di daftar dfc

In [21]:
listb = dfc["Country/Region"].values
"Belize" in listb

True

Sort semua dataframe

In [22]:
dfc.sort_values("Country/Region", inplace=True, ignore_index=True)
dfr.sort_values("Country/Region", inplace=True, ignore_index=True)
dfd.sort_values("Country/Region", inplace=True, ignore_index=True)

In [23]:
dfc

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...    27878    28424    28833
1               Albania  41.153300  20.168300  ...     1838     1891     1962
2               Algeria  28.033900   1.659600  ...    11504    11631    11771
3               Andorra  42.506300   1.521800  ...      855      855      855
4                Angola -11.202700  17.873900  ...      172      176      183
..                  ...        ...        ...  ...      ...      ...      ...
261  West Bank and Gaza  31.952200  35.233200  ...      675      784      833
262      Western Sahara  24.215500 -12.885800  ...        9        9        9
263               Yemen  15.552727  48.516388  ...      919      922      941
264              Zambia -15.416700  28.283300  ...     1430     1430     1430
265            Zimbabwe -20.000000  30.000000  ...      479      479      489

[266 rows x 155 columns]

In [24]:
dfr

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...     7962     8292     8764
1               Albania  41.153300  20.168300  ...     1114     1126     1134
2               Algeria  28.033900   1.659600  ...     8196     8324     8422
3               Andorra  42.506300   1.521800  ...      792      792      792
4                Angola -11.202700  17.873900  ...       66       66       77
..                  ...        ...        ...  ...      ...      ...      ...
248  West Bank and Gaza  31.952200  35.233200  ...      437      437      439
249      Western Sahara  24.215500 -12.885800  ...        8        8        8
250               Yemen  15.552727  48.516388  ...      288      328      347
251              Zambia -15.416700  28.283300  ...     1194     1194     1194
252            Zimbabwe -20.000000  30.000000  ...       63       63       64

[253 rows x 155 columns]

In [25]:
dfd

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...      548      569      581
1               Albania  41.153300  20.168300  ...       42       43       44
2               Algeria  28.033900   1.659600  ...      825      837      845
3               Andorra  42.506300   1.521800  ...       52       52       52
4                Angola -11.202700  17.873900  ...        8        9        9
..                  ...        ...        ...  ...      ...      ...      ...
261  West Bank and Gaza  31.952200  35.233200  ...        3        3        3
262      Western Sahara  24.215500 -12.885800  ...        1        1        1
263               Yemen  15.552727  48.516388  ...      251      254      256
264              Zambia -15.416700  28.283300  ...       11       11       11
265            Zimbabwe -20.000000  30.000000  ...        4        4        6

[266 rows x 155 columns]

Cek Kembali

In [26]:
dfc.shape

(266, 155)

In [27]:
dfr.shape

(253, 155)

In [28]:
dfd.shape

(266, 155)

Menggabungkan data dari semua dataset dfc, dfr, dan dfd

In [29]:
dfc.loc[dfc["Country/Region"] == "Australia"]
#dfr.loc[dfc["Country/Region"] == "Australia"]
#dfd.loc[dfc["Country/Region"] == "Australia"]

   Country/Region      Lat      Long  ...  6/19/20  6/20/20  6/21/20
8       Australia -31.9505  115.8605  ...      604      605      605
9       Australia -37.8136  144.9631  ...     1792     1836     1847
10      Australia -41.4545  145.9707  ...      228      228      228
11      Australia -34.9285  138.6007  ...      440      440      440
12      Australia -12.4634  130.8456  ...       29       29       29
13      Australia -33.8688  151.2093  ...     3144     3149     3151
14      Australia -35.4735  149.0124  ...      108      108      108
15      Australia -28.0167  153.4000  ...     1066     1066     1066

[8 rows x 155 columns]

In [30]:
Australi = dfc.loc[dfc["Country/Region"] == "Australia"].sum()[3:]
Australi

1/22/20       0
1/23/20       0
1/24/20       0
1/25/20       0
1/26/20       4
           ...
6/17/20    7391
6/18/20    7409
6/19/20    7411
6/20/20    7461
6/21/20    7474
Length: 152, dtype: object

In [31]:
Indonesia = dfc.loc[dfc["Country/Region"] == "Indonesia"].sum()[3:]
Indonesia

1/22/20        0
1/23/20        0
1/24/20        0
1/25/20        0
1/26/20        0
           ...
6/17/20    41431
6/18/20    42762
6/19/20    43803
6/20/20    45029
6/21/20    45891
Length: 152, dtype: object

In [32]:
latitude = dfc.loc[dfc["Country/Region"] == "Australia"].mean().values.tolist()[0:2]
latitude

[-31.996187500000005, 141.2327875]

Membuat fungsi untuk menjalankan secara otomatis

In [37]:
def hitungSum(dfx, idx):
  nama_negara=list(dfx[idx].unique())
  latitude = []
  longitude = []
  per_negara = [] #data seluruh negara, per hari
  all_n = []

  for i in nama_negara:
    latitude = dfc.loc[dfc["Country/Region"] == i, "Lat"].mean()
    longitude = dfc.loc[dfc["Country/Region"] == i, "Long"].mean()

    per_negara = dfx.loc[dfx[idx] == i].sum()[3:].values.tolist()

    per_negara.insert(0,i) #menambah nama negara
    per_negara.insert(1,latitude) 
    per_negara.insert(2,longitude)

    all_n.append(per_negara)

  return all_n

In [38]:
headerdf=dfc.columns.values.tolist() #mengambil nama-nama kolom dari dataset dfc

dfc_bersih = pd.DataFrame(hitungSum(dfc,"Country/Region"), columns=headerdf)

In [39]:
dfc_bersih

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...    27878    28424    28833
1               Albania  41.153300  20.168300  ...     1838     1891     1962
2               Algeria  28.033900   1.659600  ...    11504    11631    11771
3               Andorra  42.506300   1.521800  ...      855      855      855
4                Angola -11.202700  17.873900  ...      172      176      183
..                  ...        ...        ...  ...      ...      ...      ...
183  West Bank and Gaza  31.952200  35.233200  ...      675      784      833
184      Western Sahara  24.215500 -12.885800  ...        9        9        9
185               Yemen  15.552727  48.516388  ...      919      922      941
186              Zambia -15.416700  28.283300  ...     1430     1430     1430
187            Zimbabwe -20.000000  30.000000  ...      479      479      489

[188 rows x 155 columns]

In [40]:
dfr_bersih = pd.DataFrame(hitungSum(dfr,"Country/Region"), columns=headerdf)

In [41]:
dfr_bersih

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...     7962     8292     8764
1               Albania  41.153300  20.168300  ...     1114     1126     1134
2               Algeria  28.033900   1.659600  ...     8196     8324     8422
3               Andorra  42.506300   1.521800  ...      792      792      792
4                Angola -11.202700  17.873900  ...       66       66       77
..                  ...        ...        ...  ...      ...      ...      ...
183  West Bank and Gaza  31.952200  35.233200  ...      437      437      439
184      Western Sahara  24.215500 -12.885800  ...        8        8        8
185               Yemen  15.552727  48.516388  ...      288      328      347
186              Zambia -15.416700  28.283300  ...     1194     1194     1194
187            Zimbabwe -20.000000  30.000000  ...       63       63       64

[188 rows x 155 columns]

In [42]:
dfd_bersih = pd.DataFrame(hitungSum(dfd,"Country/Region"), columns=headerdf)

In [43]:
dfd_bersih

         Country/Region        Lat       Long  ...  6/19/20  6/20/20  6/21/20
0           Afghanistan  33.000000  65.000000  ...      548      569      581
1               Albania  41.153300  20.168300  ...       42       43       44
2               Algeria  28.033900   1.659600  ...      825      837      845
3               Andorra  42.506300   1.521800  ...       52       52       52
4                Angola -11.202700  17.873900  ...        8        9        9
..                  ...        ...        ...  ...      ...      ...      ...
183  West Bank and Gaza  31.952200  35.233200  ...        3        3        3
184      Western Sahara  24.215500 -12.885800  ...        1        1        1
185               Yemen  15.552727  48.516388  ...      251      254      256
186              Zambia -15.416700  28.283300  ...       11       11       11
187            Zimbabwe -20.000000  30.000000  ...        4        4        6

[188 rows x 155 columns]

In [44]:
dfc_bersih.shape

(188, 155)

In [45]:
dfr_bersih.shape

(188, 155)

In [46]:
dfd_bersih.shape

(188, 155)

In [48]:
dfc_bersih.isna().sum()

Country/Region    0
Lat               0
Long              0
1/22/20           0
1/23/20           0
                 ..
6/17/20           0
6/18/20           0
6/19/20           0
6/20/20           0
6/21/20           0
Length: 155, dtype: int64

In [49]:
dfr_bersih.isna().sum()

Country/Region    0
Lat               0
Long              0
1/22/20           0
1/23/20           0
                 ..
6/17/20           0
6/18/20           0
6/19/20           0
6/20/20           0
6/21/20           0
Length: 155, dtype: int64

In [50]:
dfd_bersih.isna().sum()

Country/Region    0
Lat               0
Long              0
1/22/20           0
1/23/20           0
                 ..
6/17/20           0
6/18/20           0
6/19/20           0
6/20/20           0
6/21/20           0
Length: 155, dtype: int64

Membuat Dataframe Khusus Indonesia

In [51]:
list_date=dfc_bersih.columns.values.tolist()[3:]
len(list_date)

152

## Menggabungkan Data Positif/Comfirm, Sembuh/Recorved dan Meninggal/Death


membuat list untuk menyimpan masing-masing value dari dfc, dfr, dan dfd

In [52]:
conf_id = dfc_bersih[dfc_bersih["Country/Region"]=="Indonesia"].values[0].tolist()[3:]
rec_id = dfr_bersih[dfr_bersih["Country/Region"]=="Indonesia"].values[0].tolist()[3:]
death_id = dfd_bersih[dfd_bersih["Country/Region"]=="Indonesia"].values[0].tolist()[3:]

In [53]:
len(conf_id)

152

In [54]:
len(rec_id)

152

In [55]:
len(death_id)

152

In [56]:
case_id=list((list_date,conf_id,rec_id,death_id))

In [57]:
len(case_id)

4

In [58]:
case_id

[['1/22/20',
  '1/23/20',
  '1/24/20',
  '1/25/20',
  '1/26/20',
  '1/27/20',
  '1/28/20',
  '1/29/20',
  '1/30/20',
  '1/31/20',
  '2/1/20',
  '2/2/20',
  '2/3/20',
  '2/4/20',
  '2/5/20',
  '2/6/20',
  '2/7/20',
  '2/8/20',
  '2/9/20',
  '2/10/20',
  '2/11/20',
  '2/12/20',
  '2/13/20',
  '2/14/20',
  '2/15/20',
  '2/16/20',
  '2/17/20',
  '2/18/20',
  '2/19/20',
  '2/20/20',
  '2/21/20',
  '2/22/20',
  '2/23/20',
  '2/24/20',
  '2/25/20',
  '2/26/20',
  '2/27/20',
  '2/28/20',
  '2/29/20',
  '3/1/20',
  '3/2/20',
  '3/3/20',
  '3/4/20',
  '3/5/20',
  '3/6/20',
  '3/7/20',
  '3/8/20',
  '3/9/20',
  '3/10/20',
  '3/11/20',
  '3/12/20',
  '3/13/20',
  '3/14/20',
  '3/15/20',
  '3/16/20',
  '3/17/20',
  '3/18/20',
  '3/19/20',
  '3/20/20',
  '3/21/20',
  '3/22/20',
  '3/23/20',
  '3/24/20',
  '3/25/20',
  '3/26/20',
  '3/27/20',
  '3/28/20',
  '3/29/20',
  '3/30/20',
  '3/31/20',
  '4/1/20',
  '4/2/20',
  '4/3/20',
  '4/4/20',
  '4/5/20',
  '4/6/20',
  '4/7/20',
  '4/8/20',
  '4/9/20',
  '4/10/20',
  '4/11/20',
  '4/12/20',
  '4/13/20',
  '4/14/20',
  '4/15/20',
  '4/16/20',
  '4/17/20',
  '4/18/20',
  '4/19/20',
  '4/20/20',
  '4/21/20',
  '4/22/20',
  '4/23/20',
  '4/24/20',
  '4/25/20',
  '4/26/20',
  '4/27/20',
  '4/28/20',
  '4/29/20',
  '4/30/20',
  '5/1/20',
  '5/2/20',
  '5/3/20',
  '5/4/20',
  '5/5/20',
  '5/6/20',
  '5/7/20',
  '5/8/20',
  '5/9/20',
  '5/10/20',
  '5/11/20',
  '5/12/20',
  '5/13/20',
  '5/14/20',
  '5/15/20',
  '5/16/20',
  '5/17/20',
  '5/18/20',
  '5/19/20',
  '5/20/20',
  '5/21/20',
  '5/22/20',
  '5/23/20',
  '5/24/20',
  '5/25/20',
  '5/26/20',
  '5/27/20',
  '5/28/20',
  '5/29/20',
  '5/30/20',
  '5/31/20',
  '6/1/20',
  '6/2/20',
  '6/3/20',
  '6/4/20',
  '6/5/20',
  '6/6/20',
  '6/7/20',
  '6/8/20',
  '6/9/20',
  '6/10/20',
  '6/11/20',
  '6/12/20',
  '6/13/20',
  '6/14/20',
  '6/15/20',
  '6/16/20',
  '6/17/20',
  '6/18/20',
  '6/19/20',
  '6/20/20',
  '6/21/20'],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  2,
  4,
  4,
  6,
  19,
  27,
  34,
  34,
  69,
  96,
  117,
  134,
  172,
  227,
  311,
  369,
  450,
  514,
  579,
  686,
  790,
  893,
  1046,
  1155,
  1285,
  1414,
  1528,
  1677,
  1790,
  1986,
  2092,
  2273,
  2491,
  2738,
  2956,
  3293,
  3512,
  3842,
  4241,
  4557,
  4839,
  5136,
  5516,
  5923,
  6248,
  6575,
  6760,
  7135,
  7418,
  7775,
  8211,
  8607,
  8882,
  9096,
  9511,
  9771,
  10118,
  10551,
  10843,
  11192,
  11587,
  12071,
  12438,
  12776,
  13112,
  13645,
  14032,
  14265,
  14749,
  15438,
  16006,
  16496,
  17025,
  17514,
  18010,
  18496,
  19189,
  20162,
  20796,
  21745,
  22271,
  22750,
  23165,
  23851,
  24538,
  25216,
  25773,
  26473,
  26940,
  27549,
  28233,
  28818,
  29521,
  30514,
  31186,
  32033,
  33076,
  34316,
  35295,
  36406,
  37420,
  38277,
  39294,
  40400,
  41431,
  42762,
  43803,
  45029,
  45891],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  2,
  2,
  2,
  2,
  8,
  8,
  8,
  8,
  11,
  11,
  15,
  15,
  29,
  29,
  30,
  31,
  35,
  46,
  59,
  64,
  75,
  81,
  103,
  112,
  134,
  150,
  164,
  192,
  204,
  222,
  252,
  282,
  286,
  359,
  380,
  426,
  446,
  548,
  607,
  631,
  686,
  747,
  842,
  913,
  960,
  1002,
  1042,
  1107,
  1151,
  1254,
  1391,
  1522,
  1591,
  1665,
  1876,
  1954,
  2197,
  2317,
  2381,
  2494,
  2607,
  2698,
  2881,
  3063,
  3287,
  3518,
  3803,
  3911,
  4129,
  4324,
  4467,
  4575,
  4838,
  5057,
  5249,
  5402,
  5642,
  5877,
  6057,
  6240,
  6492,
  7015,
  7308,
  7637,
  7935,
  8406,
  8892,
  9443,
  9907,
  10498,
  10904,
  11414,
  12129,
  12636,
  13213,
  13776,
  14531,
  15123,
  15703,
  16243,
  16798,
  17349,
  17883,
  18404],
 [0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  4,
  5,
  5,
  5,
  5,
  19,
  25,
  32,
  38,
  48,
  49,
  55,
  58,
  78,
  87,
  102,
  114,
  122,
  136,
  157,
  170,
  181,
  191,
  198,
  209,
  221,
  240,
  280,
  306,
  327,
  373,
  399,
  459,
  469,
  496,
  520,
  535,
  582,
  590,
  616,
  635,
  647,
  689,
  720,
  743,
  765,
  773,
  784,
  792,
  800,
  831,
  845,
  864,
  872,
  895,
  930,
  943,
  959,
  973,
  991,
  1007,
  1028,
  1043,
  1076,
  1089,
  1148,
  1191,
  1221,
  1242,
  1278,
  1326,
  1351,
  1372,
  1391,
  1418,
  1473,
  1496,
  1520,
  1573,
  1613,
  1641,
  1663,
  1698,
  1721,
  1770,
  1801,
  1851,
  1883,
  1923,
  1959,
  2000,
  2048,
  2091,
  2134,
  2198,
  2231,
  2276,
  2339,
  2373,
  2429,
  2465]]

Mengkonvers Case_id ke datafram

In [59]:
df_id=pd.DataFrame(case_id).T

In [60]:
df_id.columns=["tanggal","positif","sembuh","meninggal"]

In [61]:
df_id

     tanggal positif sembuh meninggal
0    1/22/20       0      0         0
1    1/23/20       0      0         0
2    1/24/20       0      0         0
3    1/25/20       0      0         0
4    1/26/20       0      0         0
..       ...     ...    ...       ...
147  6/17/20   41431  16243      2276
148  6/18/20   42762  16798      2339
149  6/19/20   43803  17349      2373
150  6/20/20   45029  17883      2429
151  6/21/20   45891  18404      2465

[152 rows x 4 columns]